### ISSUE TITLE
PdeP 2021-Tecnicas de Combate

### ISSUE THREAD

**Issue by jguerreno** [jguerreno/2021-f-Tecnicas-de-Combate#1]
Hola quería saber si me podrían decir como esta la resolución del ejercicio. 
Muchas Gracias.
@asanzo
@PalumboN
@Danymmereles
@ezequielPereyra

**Comment by asanzo** [comment]
Fijate que decir entre200y400 = between 200 400 no agrega mucho, podés directamente usar between 200 400 , que es lo mismo. 

Muy distinto es usar focalizar = take 7, donde eso sí está bien porque estás aprovechando para escribir en tu código la idea de "focalizar", que está en el dominio.

El resto genial.

**Comment by jguerreno** [comment]
Muchas gracias profe, ya lo arregle.
